### ISSUE TITLE
make `start-operator` fails due to gas estimation error

### ISSUE THREAD

**Issue by diyahir** [Layr-Labs/hello-world-avs#20]
I am able to run the commands running on an M1 mac locally, looks like it's calling the holesky rpc not the local one

```bash
make start-chain-with-contracts-deployed
```
and
```bash
make spam-rust-tasks
```

but
```bash
make start-operator
```

produces this error

```error
Error in main function: <ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (23500)\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xd94fb0ac\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x691ade04ccb9e83d354372dbec2b9a93908a9bc6\",\"to\":\"0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9\",\"data\":\"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc-holesky.rockx.com"},"method":"estimateGas","transaction":{"from":"0x691aDE04CcB9E83d354372DBEc2b9A93908a9BC6","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0xd94fb0ac"},"to":"0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9","data":"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000","type":2,"accessList":null}}, tx={"data":"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000","to":{},"from":"0x691aDE04CcB9E83d354372DBEc2b9A93908a9BC6","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0xd94fb0ac"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
    at Logger.makeError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/abstract-signer/lib/index.js:365:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 7) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (23500)\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xd94fb0ac\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x691ade04ccb9e83d354372dbec2b9a93908a9bc6\",\"to\":\"0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9\",\"data\":\"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc-holesky.rockx.com"}, method="estimateGas", transaction={"from":"0x691aDE04CcB9E83d354372DBEc2b9A93908a9BC6","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0xd94fb0ac"},"to":"0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9","data":"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000","type":2,"accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
      at Logger.makeError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:238:21)
      at Logger.throwError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:247:20)
      at checkError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:175:16)
      at JsonRpcProvider.<anonymous> (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
      at step (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.throw (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at rejected (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
    code: 'UNPREDICTABLE_GAS_LIMIT',
    error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (23500)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xd94fb0ac\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x691ade04ccb9e83d354372dbec2b9a93908a9bc6\",\"to\":\"0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9\",\"data\":\"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":49,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc-holesky.rockx.com", code=SERVER_ERROR, version=web/5.7.1)
        at Logger.makeError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at /Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/web/lib/index.js:313:32
        at step (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/Users/diyahircampos/Files/Github/hello-world-avs/node_modules/@ethersproject/web/lib/index.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      reason: 'processing response error',
      code: 'SERVER_ERROR',
      body: '{"jsonrpc":"2.0","id":49,"error":{"code":-32000,"message":"gas required exceeds allowance (23500)"}}\n',
      error: [Error],
      requestBody: '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0xd94fb0ac","maxPriorityFeePerGas":"0x59682f00","from":"0x691ade04ccb9e83d354372dbec2b9a93908a9bc6","to":"0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9","data":"0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000"}],"id":49,"jsonrpc":"2.0"}',
      requestMethod: 'POST',
      url: 'https://rpc-holesky.rockx.com'
    },
    method: 'estimateGas',
    transaction: {
      from: '0x691aDE04CcB9E83d354372DBEc2b9A93908a9BC6',
      maxPriorityFeePerGas: [BigNumber],
      maxFeePerGas: [BigNumber],
      to: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
      data: '0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000',
      type: 2,
      accessList: null
    }
  },
  tx: {
    data: '0x0f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000',
    to: Promise { '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9' },
    from: '0x691aDE04CcB9E83d354372DBEc2b9A93908a9BC6',
    type: 2,
    maxFeePerGas: BigNumber { _hex: '0xd94fb0ac', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    nonce: Promise { 140 },
    gasLimit: Promise { <rejected> [Circular *1] },
    chainId: Promise { 17000 }
  }
}
```

**Comment by damienen** [comment]
Hi! I am having this issue as well. Any solution?

**Comment by Gajesh2007** [comment]
can u pull the latest commit?

**Comment by damienen** [comment]
I am already on the latest commit: 1615d132d90a0c9b608a579b56bf4838e234eb04

Only forked a few hours ago

**Comment by damienen** [comment]
Update: if I set a hardcoded gas limit the error changes to this one:
Error in main function: Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":51,\"error\":{\"code\":-32003,\"message\":\"Insufficient funds for gas * price + value\"}}","error":{"code":-32003},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f90112827a69808459682f008459682f4c830186a094cf7ed3acca5a467e9e704c703e8d87f634fb0fc980b8a40f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000c080a0388cb693ac7fa17c09944045e6215899d71631ba13c9eedc0c1065cd490ebdffa025792b65dbee15b9af5d0f23401c7d2b04b578398f432a11648b2a01265c2929\"],\"id\":51,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://127.0.0.1:8545"}, method="sendTransaction", transaction="0x02f90112827a69808459682f008459682f4c830186a094cf7ed3acca5a467e9e704c703e8d87f634fb0fc980b8a40f589e59000000000000000000000000691ade04ccb9e83d354372dbec2b9a93908a9bc60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000c080a0388cb693ac7fa17c09944045e6215899d71631ba13c9eedc0c1065cd490ebdffa025792b65dbee15b9af5d0f23401c7d2b04b578398f432a11648b2a01265c2929", code=INSUFFICIENT_FUNDS, version=providers/5.7.2)

**Comment by damienen** [comment]
Update 2: I managed to make the operator work by:
1. Going into the anvil docker logs and copying a private key from there
2. Putting that private key in .env, replacing the default PRIVATE_KEY

**Comment by diyahir** [comment]
I am seeing the same issue, @Gajesh2007 I believe this issue was closed early

**Comment by damienen** [comment]
@diyahir see my "Update 2" comment. There's a good chance you will have it solved like that as well
