### ISSUE TITLE
Cannot start-operator (with JS) on a private POS Ethereum DevNet

### ISSUE THREAD

**Issue by wawrzek** [Layr-Labs/hello-world-avs#30]
I try to deploy Hello World AVS on the iv1 devnet (https://github.com/ivy-net/iv1/tree/feature/hello-world). The on-chain deployments is fine. The off-chain parts are problematic. 

I can start operator with _rust_ after readding commented lines with gasPrice and gasLimits (as suggested for the Holesky network). The _js_ path is not so happy. With the gasLimit the EL registration passes. However, the tx2 (AVS registration) fails with:
```
Error in main function: Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x0363419491d913c5e21c236931bb744a21eafa660f2be1faa5202c4f39f0e67a", transaction={"type":2,"chainId":32382,"nonce":41,"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x7a1200"},"maxFeePerGas":{"type":"BigNumber","hex":"0x7a1200"},"gasPrice":null,"gasLimit":{"type":"BigNumber","hex":"0x0493e0"},"to":"0x7e86dd3aed060037003Bd2077BEFb88278a83935","value":{"type":"BigNumber","hex":"0x00"},"data":"0x0a601a12000000000000000000000000123463a4b065722e99115d6c222f267d9cabb524000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000605ab9c761bbde56a0efaa448edb875d70d420490ef9eab7cbe63bff905463b3b400000000000000000000000000000000000000000000000000000000668413930000000000000000000000000000000000000000000000000000000000000041104b72459d6cde7df58e53d85cccb66fa7772ac0a83a80f43fa322a05358bd257a2e35b7416465dc27c6cf42d5f985a30ffeec3585fec181870b2435a1eb15451b00000000000000000000000000000000000000000000000000000000000000","accessList":[],"hash":"0x0363419491d913c5e21c236931bb744a21eafa660f2be1faa5202c4f39f0e67a","v":0,"r":"0x6e37efe5e476af5ab5217f242400782d00df1f27c61701f79e5a6f4a0c5a6d42","s":"0x7de86c3d780aa85d14ddd562ae4baa9c4138d8bb4d0d1951e6b5849499a0f6c4","from":"0x123463a4B065722E99115D6c222f267d9cABb524","confirmations":0}, receipt={"to":"0x7e86dd3aed060037003Bd2077BEFb88278a83935","from":"0x123463a4B065722E99115D6c222f267d9cABb524","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x7a49"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xcccbdebd0ad7c2ac8a314abb86a81e9b9b0b1a386d0dd64a5f984c5a9cbbb250","transactionHash":"0x0363419491d913c5e21c236931bb744a21eafa660f2be1faa5202c4f39f0e67a","logs":[],"blockNumber":87,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x7a49"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x7a1200"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/Users/wawrzek/Ethereum/IvyNet/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/wawrzek/Ethereum/IvyNet/hello-world-avs/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/Users/wawrzek/Ethereum/IvyNet/hello-world-avs/node_modules/@ethersproject/providers/lib/base-provider.js:1693:36)
    at step (/Users/wawrzek/Ethereum/IvyNet/hello-world-avs/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/wawrzek/Ethereum/IvyNet/hello-world-avs/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/wawrzek/Ethereum/IvyNet/hello-world-avs/node_modules/@ethersproject/providers/lib/base-provider.js:20:58) {
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0x0363419491d913c5e21c236931bb744a21eafa660f2be1faa5202c4f39f0e67a',
  transaction: {
    type: 2,
    chainId: 32382,
    nonce: 41,
    maxPriorityFeePerGas: BigNumber { _hex: '0x7a1200', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x7a1200', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x0493e0', _isBigNumber: true },
    to: '0x7e86dd3aed060037003Bd2077BEFb88278a83935',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x0a601a12000000000000000000000000123463a4b065722e99115d6c222f267d9cabb524000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000605ab9c761bbde56a0efaa448edb875d70d420490ef9eab7cbe63bff905463b3b400000000000000000000000000000000000000000000000000000000668413930000000000000000000000000000000000000000000000000000000000000041104b72459d6cde7df58e53d85cccb66fa7772ac0a83a80f43fa322a05358bd257a2e35b7416465dc27c6cf42d5f985a30ffeec3585fec181870b2435a1eb15451b00000000000000000000000000000000000000000000000000000000000000',
    accessList: [],
    hash: '0x0363419491d913c5e21c236931bb744a21eafa660f2be1faa5202c4f39f0e67a',
    v: 0,
    r: '0x6e37efe5e476af5ab5217f242400782d00df1f27c61701f79e5a6f4a0c5a6d42',
    s: '0x7de86c3d780aa85d14ddd562ae4baa9c4138d8bb4d0d1951e6b5849499a0f6c4',
    from: '0x123463a4B065722E99115D6c222f267d9cABb524',
    confirmations: 0,
    wait: [Function (anonymous)]
  },
  receipt: {
    to: '0x7e86dd3aed060037003Bd2077BEFb88278a83935',
    from: '0x123463a4B065722E99115D6c222f267d9cABb524',
    contractAddress: null,
    transactionIndex: 0,
    gasUsed: BigNumber { _hex: '0x7a49', _isBigNumber: true },
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    blockHash: '0xcccbdebd0ad7c2ac8a314abb86a81e9b9b0b1a386d0dd64a5f984c5a9cbbb250',
    transactionHash: '0x0363419491d913c5e21c236931bb744a21eafa660f2be1faa5202c4f39f0e67a',
    logs: [],
    blockNumber: 87,
    confirmations: 1,
    cumulativeGasUsed: BigNumber { _hex: '0x7a49', _isBigNumber: true },
    effectiveGasPrice: BigNumber { _hex: '0x7a1200', _isBigNumber: true },
    status: 0,
    type: 2,
    byzantium: true
  }
```

**Comment by stevennevins** [comment]
@wawrzek are you still facing issues?

**Comment by stevennevins** [comment]
Feel free to open if you're still facing the same issue and we can help resolve. the linked 404'd for me so I wasn't able to test
